parameters:
    hip_i18n.router.class: Hip\I18nRoutingBundle\Router\I18nRouter

services:
    hip_i18n.router:
       class: %hip_i18n.router.class%
       arguments: [@service_container, %router.resource%, @logger]